version: '3.4'

services:
  masstransitdemo.api:
    image: ${DOCKER_REGISTRY-}masstransitdemoapi
    build:
      context: .
      dockerfile: MassTransitDemo.Api/Dockerfile
  rabbitmq:
    image: rabbitmq:3-management
    hostname: MassTransitDemo-rabbit
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@MassTransitDemo-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
